// SPDX-License-Identifier: AGPL-3.0-or-later
import { describe, expect, it } from 'vitest';
import { formatDuration, parseGcodeMetadata } from '../src/gcode-metadata.js';

const ORCA_SAMPLE = `
; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.1 on 2026-09-09 at 10:57:40
; total layer number: 150
; filament_density: 1.27
; filament_diameter: 1.75
; max_z_height: 30.00
; HEADER_BLOCK_END

; ...toolpaths...

; total filament used [mm] : 3210.5
; total filament used [cm3] : 7.72
; total filament used [g] : 8.32
; total filament cost : 0.42
; estimated printing time (normal mode) : 45m 12s
; estimated printing time (silent mode) : 51m 5s
`.trim();

describe('parseGcodeMetadata', () => {
  it('parses OrcaSlicer header + trailer comments', () => {
    const m = parseGcodeMetadata(ORCA_SAMPLE);
    expect(m.slicerName).toBe('OrcaSlicer');
    expect(m.slicerVersion).toBe('2.3.1');
    expect(m.layerCount).toBe(150);
    expect(m.maxZ).toBeCloseTo(30);
    expect(m.filamentDensity).toBeCloseTo(1.27);
    expect(m.filamentDiameter).toBeCloseTo(1.75);
    expect(m.filamentMm).toBeCloseTo(3210.5);
    expect(m.filamentCm3).toBeCloseTo(7.72);
    expect(m.filamentGrams).toBeCloseTo(8.32);
    expect(m.filamentCost).toBeCloseTo(0.42);
    expect(m.printTimeSeconds).toBe(45 * 60 + 12);
    expect(m.printTimeSilentSeconds).toBe(51 * 60 + 5);
  });

  it('falls back to generic "estimated printing time" when normal/silent tags are absent', () => {
    const m = parseGcodeMetadata('; estimated printing time: 1h 30m');
    expect(m.printTimeSeconds).toBe(90 * 60);
  });

  it('parses durations across all units (d/h/m/s)', () => {
    const m = parseGcodeMetadata('; estimated printing time (normal mode): 1d 2h 30m 45s');
    expect(m.printTimeSeconds).toBe(86400 + 2 * 3600 + 30 * 60 + 45);
  });

  it('derives cm3 and grams from mm + diameter + density when trailer is missing', () => {
    const partial = [
      '; filament_density: 1.24',
      '; filament_diameter: 1.75',
      '; total filament used [mm]: 1000',
    ].join('\n');
    const m = parseGcodeMetadata(partial);
    // πr²·L = π · (1.75/2)² · 1000 = 2405.3 mm³ = 2.405 cm³
    expect(m.filamentCm3).toBeCloseTo(2.405, 2);
    // grams = 2.405 · 1.24
    expect(m.filamentGrams).toBeCloseTo(2.982, 2);
  });

  it('returns undefined fields when comments are missing', () => {
    const m = parseGcodeMetadata('G28\nG1 X10 Y10');
    expect(m.printTimeSeconds).toBeUndefined();
    expect(m.layerCount).toBeUndefined();
    expect(m.filamentMm).toBeUndefined();
  });

  it('extracts bed and nozzle target temperatures', () => {
    const gcode = [
      'G28',
      'M104 S220',
      'M140 S60',
      'M109 S220',
      'M190 S60',
      'START_PRINT EXTRUDER_TEMP=220 BED_TEMP=60',
    ].join('\n');
    const m = parseGcodeMetadata(gcode);
    expect(m.nozzleTempC).toBe(220);
    expect(m.bedTempC).toBe(60);
  });

  it('falls back to Klipper macro args when no M104/M140 present', () => {
    const gcode = 'G28\nSTART_PRINT EXTRUDER_TEMP=255 BED_TEMP=85';
    const m = parseGcodeMetadata(gcode);
    expect(m.nozzleTempC).toBe(255);
    expect(m.bedTempC).toBe(85);
  });

  it('ignores S0 (heater off) in temp extraction', () => {
    const gcode = 'M140 S0\nM104 S0\nM140 S85\nM104 S255';
    const m = parseGcodeMetadata(gcode);
    expect(m.bedTempC).toBe(85);
    expect(m.nozzleTempC).toBe(255);
  });

  it('handles Windows line endings', () => {
    const m = parseGcodeMetadata('; total layer number: 42\r\n; max_z_height: 8.4\r\n');
    expect(m.layerCount).toBe(42);
    expect(m.maxZ).toBeCloseTo(8.4);
  });
});

describe('formatDuration', () => {
  it('formats seconds only', () => expect(formatDuration(45)).toBe('45s'));
  it('formats minutes + seconds', () => expect(formatDuration(125)).toBe('2m 5s'));
  it('formats hours + minutes', () => expect(formatDuration(3600 + 15 * 60 + 30)).toBe('1h 15m'));
  it('renders em-dash for zero/undefined', () => {
    expect(formatDuration(undefined)).toBe('—');
    expect(formatDuration(0)).toBe('—');
    expect(formatDuration(-5)).toBe('—');
  });
});
