// SPDX-License-Identifier: AGPL-3.0-or-later
// Parse the metadata OrcaSlicer/PrusaSlicer/SuperSlicer embed as comments in
// the emitted g-code. These comments are the slicer's own estimate — always
// more accurate than deriving from raw toolpaths since the slicer knew about
// accel, jerk, and retraction.
//
// Comments seen in the wild (OrcaSlicer 2.x):
//   ; total layer number: 150
//   ; max_z_height: 30.00
//   ; filament_density: 1.27
//   ; filament_diameter: 1.75
//   ; total filament used [mm]: 3210.5
//   ; total filament used [cm3]: 7.72
//   ; total filament used [g]: 8.32
//   ; total filament weight [g]: 8.32
//   ; total filament cost: 0.42
//   ; estimated printing time (normal mode): 45m 12s
//   ; estimated printing time (silent mode): 51m 5s

export interface GcodeMetadata {
  printTimeSeconds?: number;
  printTimeSilentSeconds?: number;
  filamentMm?: number;
  filamentCm3?: number;
  filamentGrams?: number;
  filamentCost?: number;
  filamentDensity?: number;      // g/cm3
  filamentDiameter?: number;     // mm
  layerCount?: number;
  maxZ?: number;                 // mm
  slicerName?: string;
  slicerVersion?: string;
  /** Bed temperature actually commanded, in °C. Reads `M140 S<n>` / `M190 S<n>`
   *  and Klipper macro args (`BED_TEMP=<n>`). Returns the first value seen. */
  bedTempC?: number;
  /** Nozzle temperature actually commanded, in °C. Reads `M104 S<n>` /
   *  `M109 S<n>` and Klipper macro args (`EXTRUDER_TEMP=<n>`). */
  nozzleTempC?: number;
}

/** Turn "45m 12s" / "1h 30m 5s" / "5m" / "10s" / "1d 3h 20m" into seconds. */
function parseDuration(text: string): number | undefined {
  let total = 0;
  let matched = false;
  const patterns: Array<[RegExp, number]> = [
    [/(\d+(?:\.\d+)?)\s*d/i, 86400],
    [/(\d+(?:\.\d+)?)\s*h/i, 3600],
    [/(\d+(?:\.\d+)?)\s*m(?!s)/i, 60],
    [/(\d+(?:\.\d+)?)\s*s/i, 1],
  ];
  for (const [re, mult] of patterns) {
    const m = text.match(re);
    if (m) { total += parseFloat(m[1]) * mult; matched = true; }
  }
  return matched ? total : undefined;
}

function firstFloat(re: RegExp, text: string): number | undefined {
  const m = text.match(re);
  if (!m) return undefined;
  const n = parseFloat(m[1]);
  return Number.isFinite(n) ? n : undefined;
}

/** Extract slicer-embedded metadata from a gcode blob. Scans the whole file
 *  since Orca often puts totals near the end. Returns partial info — every
 *  field is optional. */
export function parseGcodeMetadata(gcode: string): GcodeMetadata {
  const out: GcodeMetadata = {};

  // Print time (normal + optional silent mode).
  const timeNormal = gcode.match(/;\s*estimated printing time\s*\(normal mode\)\s*:\s*([^\r\n]+)/i);
  if (timeNormal) out.printTimeSeconds = parseDuration(timeNormal[1]);
  const timeSilent = gcode.match(/;\s*estimated printing time\s*\(silent mode\)\s*:\s*([^\r\n]+)/i);
  if (timeSilent) out.printTimeSilentSeconds = parseDuration(timeSilent[1]);
  if (out.printTimeSeconds === undefined) {
    // Fallback for slicers that don't tag "normal mode".
    const generic = gcode.match(/;\s*estimated printing time\s*:\s*([^\r\n]+)/i);
    if (generic) out.printTimeSeconds = parseDuration(generic[1]);
  }

  out.filamentMm = firstFloat(/;\s*total filament used\s*\[mm\]\s*:\s*(-?\d+(?:\.\d+)?)/i, gcode);
  out.filamentCm3 = firstFloat(/;\s*total filament used\s*\[cm3\]\s*:\s*(-?\d+(?:\.\d+)?)/i, gcode);
  out.filamentGrams =
    firstFloat(/;\s*total filament weight\s*\[g\]\s*:\s*(-?\d+(?:\.\d+)?)/i, gcode) ??
    firstFloat(/;\s*total filament used\s*\[g\]\s*:\s*(-?\d+(?:\.\d+)?)/i, gcode);
  out.filamentCost = firstFloat(/;\s*total filament cost\s*:\s*(-?\d+(?:\.\d+)?)/i, gcode);
  out.filamentDensity = firstFloat(/;\s*filament_density\s*:\s*(-?\d+(?:\.\d+)?)/i, gcode);
  out.filamentDiameter = firstFloat(/;\s*filament_diameter\s*:\s*(-?\d+(?:\.\d+)?)/i, gcode);
  out.layerCount = firstFloat(/;\s*total layer number\s*:\s*(\d+)/i, gcode);
  out.maxZ = firstFloat(/;\s*max_z_height\s*:\s*(-?\d+(?:\.\d+)?)/i, gcode);

  // Derive cm3 and grams from mm + density/diameter if the slicer skipped them.
  if (out.filamentMm !== undefined && out.filamentDiameter !== undefined) {
    if (out.filamentCm3 === undefined) {
      const r = out.filamentDiameter / 2;
      out.filamentCm3 = (Math.PI * r * r * out.filamentMm) / 1000;
    }
    if (out.filamentGrams === undefined && out.filamentDensity !== undefined && out.filamentCm3 !== undefined) {
      out.filamentGrams = out.filamentCm3 * out.filamentDensity;
    }
  }

  const gen = gcode.match(/;\s*generated by\s+(\S+)\s+(\S+)/i);
  if (gen) {
    out.slicerName = gen[1];
    out.slicerVersion = gen[2];
  }

  // Command temperatures: what will actually reach the printer. Scan for the
  // first non-zero value from any of {M140/M190 (bed), M104/M109 (nozzle),
  // or Klipper macro args}. `S0` disables heating and shouldn't be reported
  // as "the target".
  const firstNonZero = (re: RegExp): number | undefined => {
    for (const m of gcode.matchAll(re)) {
      const n = parseFloat(m[1]);
      if (Number.isFinite(n) && n > 0) return n;
    }
    return undefined;
  };
  out.bedTempC =
    firstNonZero(/^(?:M14?0|M19?0)\s+S(-?\d+(?:\.\d+)?)/gim) ??
    firstNonZero(/\bBED_TEMP\s*=\s*(-?\d+(?:\.\d+)?)/gi);
  out.nozzleTempC =
    firstNonZero(/^(?:M10?4|M10?9)\s+S(-?\d+(?:\.\d+)?)/gim) ??
    firstNonZero(/\bEXTRUDER_TEMP\s*=\s*(-?\d+(?:\.\d+)?)/gi);

  return out;
}

export function formatDuration(seconds: number | undefined): string {
  if (!seconds || !Number.isFinite(seconds) || seconds <= 0) return '—';
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0) return `${h}h ${m}m`;
  if (m > 0) return `${m}m ${s}s`;
  return `${s}s`;
}
